#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

systemProp.org.gradle.internal.publish.checksums.insecure=true

mavenCentralUsername=sgY9jS
mavenCentralPassword=bPLB7dZF67Qp2aGm4N0fd76Z2nVH5svzG
signing.keyId=73BD1657
signing.password=9936045398@Aa
signing.secretKeyRingFile=/Users/apple/sign.gpg